# Generated by Django 5.2 on 2025-04-27 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_ids', models.JSONField(default=list, help_text="List of user's expense IDs")),
            ],
        ),
    ]
