# Generated by Django 5.2 on 2025-04-27 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(choices=[('food', 'Food'), ('transportation', 'Transportation'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('groceries', 'Groceries'), ('leisure', 'Leisure'), ('electronics', 'Electronics'), ('utilities', 'Utilities'), ('clothing', 'Clothing'), ('health', 'Health'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
